#pragma once

#include <stdint.h>
#include <stddef.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct gen_generator gen_generator;
typedef struct gen_data gen_data;
typedef struct gen_tensor gen_tensor;

gen_generator* gen_generator_create(size_t workers);
void gen_generator_destroy(gen_generator* generator);

void gen_data_acquire(gen_data* data);
uint16_t gen_data_bitness(const gen_data* data);
size_t gen_data_cases(const gen_data* data);
size_t gen_data_reps(const gen_data* data);
// Transfers buffer ownership to the caller. The returned pointer must later be
// passed to gen_float_buffer_destroy(). Each buffer may be taken exactly once.
float* gen_data_take_values(gen_data* data);
float* gen_data_take_targets(gen_data* data);
void gen_data_release(gen_generator* generator, gen_data* data);

void gen_tensor_acquire(gen_tensor* tensor);
// Transfers buffer ownership to the caller. May be called exactly once.
float* gen_tensor_take_values(gen_tensor* tensor);
void gen_tensor_release(gen_generator* generator, gen_tensor* tensor);

// Frees a float buffer transferred out of a data or tensor handle.
void gen_float_buffer_destroy(float* buffer);

/*******************************************************************************
 * There are 3 types of boolean functions served by this library.
 * 1: Backed by binary tree: `gen_tree_*`
 *    Tree is generated by Rémy-like algorith for tree size of up to 2^16.
 *    Bitness can vary from 10 to 256.
 *    `depth` and `nodes` computed from supporting tree.
 *
 * 2: Backed by random table. `gen_table_*`
 *    Bitness can vary from 4 to 256.
 *    For bitness in [4, 6] represented as uint64_t.
 *    For bitness in [7, 16] represented as std::vector<bool>.
 *    For higher bitness computed when queried + memoized.
 *    `depth` and `nodes` computed for bitness in [4, 16].
 *
 * 3: Backed by circuits from benchmarks.
 ******************************************************************************/

/********************************* 1st type ***********************************/

// Minimum bitness for which trees are constructed.
uint16_t gen_min_tree_bitness();

size_t gen_tree_cases_number(uint16_t bitness);

// Input: 0/1 string of length bitness
// Output: 0/1 string of length 2 * bitness + 1
// Output consists of the input [bitness bits] followed by f(input) [1 bit]
// followed by f(input with flipped i-th bit) [1 bit x bitness]
const char* gen_tree_value(uint16_t bitness, size_t case_id, const char* input);

// Enqueues a C++-owned typed batch. Values have shape
// cases x reps x (2 * bitness + 1); targets have shape cases.
gen_data* gen_tree_value_tensor(
    gen_generator* generator,
    uint16_t bitness,
    size_t cases,
    size_t reps,
    uint64_t seed);

/********************************* 2nd type ***********************************/

// Maximum bitness for which table is representable as decision tree.
uint16_t gen_table_solvable_bitness();

size_t gen_table_cases_number(uint16_t bitness);

// Input: 0/1 string of length bitness
// Output: 0/1 string of length 2 * bitness + 1
// Output consists of the input [bitness bits] followed by f(input) [1 bit]
// followed by f(input with flipped i-th bit) [1 bit x bitness]
const char* gen_table_value(uint16_t bitness, size_t case_id, const char* input);

// For bitness above gen_table_solvable_bitness(), targets are null and the
// first restriction chunk is generated together with the values.
gen_data* gen_table_value_tensor(
    gen_generator* generator,
    uint16_t bitness,
    size_t cases,
    size_t reps,
    size_t restriction_chunk_cases,
    uint64_t seed);

// Enqueues restrictions for a contiguous range of cases from recursive table
// data. Output shape: cases x (2 * bitness) x reps x (2 * bitness - 1).
gen_tensor* gen_table_restrictions_tensor(
    gen_generator* generator,
    gen_data* table_data,
    size_t first_case,
    size_t cases);

/********************************* 3rd type ***********************************/

// Returns sorted newline-separated circuit set names discovered in circuits/
const char* gen_circuit_sets();

// Returns sorted newline-separated circuit case names for a set
const char* gen_circuit_cases(const char* set_name);

size_t gen_circuit_inputs(const char* set_name, const char* case_name);
size_t gen_circuit_outputs(const char* set_name, const char* case_name);

// Computes value samples for an AIG circuit.
// For sequential circuits, input_state contains primary inputs followed by latch state bits.
// Return length is N + M * (N + 1), where N = inputs and M = outputs:
// input_state + outputs(input_state) + outputs(input_state with flipped i-th bit).
const char* gen_circuit_value(const char* set_name, const char* case_name, const char* input_state);

#ifdef __cplusplus
}
#endif
