training:
  iterations: 5
  epochs: 100
  batch_size: 256
  rmse_threshold: 0.05
  train_samples: 65536
  validation_samples: 1024
  sample_structure:
    points_in_batch: 64
    batches: 2
  bitness_from: 10
  bitness_to: 11
  seed: 239
  model_dir: /tmp/circus
