training:
  iterations: 1
  epochs: 100
  batch_size: 32
  rmse_threshold: 0.05
  train_samples: 64
  validation_samples: 32
  points_per_sample: 128
  bitness_from: 16
  bitness_to: 17
  seed: 239
  model_dir: /tmp/circus

model:
  name: deepset
  phi_hidden: 512
  phi_out: 256
  rho_hidden: 512
  dropout: 0.3

optimizer:
  name: adam
  lr: 0.001
  scheduler:
    name: reduce_lr_on_plateau
    patience: 5
    factor: 0.5
