training:
  iterations: 100
  epochs: 100
  batch_size: 256
  rmse_threshold: 0.05
  train_samples: 65536
  validation_samples: 1024
  sample_structure:
    points_in_batch: 128
    batches: 8
  bitness_from: 10
  bitness_to: 19
  seed: 239
  model_dir: /tmp/circus

model:
  name: deepset
  phi_hidden: 512
  phi_out: 256
  rho_hidden: 512
  dropout: 0.3

optimizer:
  name: adam
  lr: 0.001
  scheduler:
    name: reduce_lr_on_plateau
    patience: 5
    factor: 0.5
