#!/usr/bin/env bash
set -euo pipefail

# Removes generated build trees and LaTeX artifacts; everything it deletes is
# regenerated by `scripts/build.sh`, `scripts/test.sh`, or a LaTeX run.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

remove() {
    [ -e "$1" ] || return 0
    echo "removing ${1#"$ROOT"/}"
    rm -rf "$1"
}

# Build trees
remove "$ROOT/build"
remove "$ROOT/cpp/build"
remove "$ROOT/cpp/build-asan"
remove "$ROOT/cpp/build-perf"
for dir in "$ROOT"/cmake-build-*; do
    remove "$dir"
done

# LaTeX artifacts next to the sources.
while IFS= read -r -d '' file; do
    remove "$file"
done < <(find "$ROOT" -path "$ROOT/.git" -prune -o -type f \( \
    -name "*.aux" -o -name "*.bbl" -o -name "*.blg" -o -name "*.fdb_latexmk" \
    -o -name "*.fls" -o -name "*.lof" -o -name "*.log" -o -name "*.lot" \
    -o -name "*.out" -o -name "*.pdf" -o -name "*.toc" \
    \) -print0)
